### ISSUE TITLE
meta tag 추가, favicon 추가, 폰트, 모듈 최적화

### ISSUE THREAD

**Issue by pds0309** [Almondia/meca_front#120]
## Summary

meta tag 추가, favicon 추가, 폰트 최적화

<br>

## TODO

- [x] 페이지 meta tag 추가
- [x] favicon 추가
- [x] 폰트 fout 발생하는 문제 최적화
- [x] 필요한 부분 코드 스플리팅

<br>
