### ISSUE TITLE
카테고리 썸네일, ImageCropper 관련 오류 개선

### ISSUE THREAD

**Issue by pds0309** [Almondia/meca_front#173]
## Summary

카테고리 썸네일 관련 오류 개선

<br>

## TODO

- [x] 카테고리 dialog 다른 항목 변경 시 blob 이미지 재호출되는 문제 개선
- [x] ImageCropper 자른 이미지 모바일에서 식별안되는 문제
- [x] UserProfile Image에 ImageCropper 기능 추가

<br>
