### ISSUE TITLE
일부 UI관련 수정

### ISSUE THREAD

**Issue by pds0309** [Almondia/meca_front#199]
## Summary

자잘자잘

<br>

## TODO

- [x] Icon Input Text영역과 Icon간 간격 이상한 부분 수정
- [x] 카드 상세 페이지 AvatarUser 본인 페이지 아닌 경우 중앙 정렬되는 부분 수정
- [x] 로그아웃 시 route.push보다 cache가 먼저 만료되어 404페이지 보이는 부분 수정

<br>
