### ISSUE TITLE
일부 UI 요소 개선

### ISSUE THREAD

**Issue by pds0309** [Almondia/meca_front#219]
## Summary

일부 UI 요소 개선

<br>

## TODO

- [x] Input 자동완성 제거
- [x] 문제 유형 태그 대비가 충분하지 않은 부분 색상 개선
- [x] 메인 Carousel 다크 모드에서 대비가 눈에 너무 띄는 부분 개선
- [x] 객관식 문제 Hidden Radio 식별되는 부분 개선
- [x] 목록 검색 시 Enter로 가능하도록 추가
- [x] 카드 UI 개선 (다크모드 시 어색함)
- [x] 에디터 UI 일관성 없는 부분 개선

<br>
