### ISSUE TITLE
Write Editor UI 일부 개선

### ISSUE THREAD

**Issue by pds0309** [Almondia/meca_front#240]
## Summary

Write Editor UI 일부 개선

<br>

## TODO

- [x] 이미지 업로드 UI 추가(기존 아이콘 너무 작음)
- [x] placeholder 내용 수정 및 props로 전달받아 구성되도록 수정
- [x] 카드 작성 시 question 항목에 작성한 내용이 퀴즈타입을 변경해도 유지되도록 수정
