### ISSUE TITLE
웹 접근성 관련 일부 UI 개선

### ISSUE THREAD

**Issue by pds0309** [Almondia/meca_front#249]
## Summary

웹 접근성 관련 일부 UI 개선

<br>

## TODO

- [x] 추천 버튼에 접근 가능한 이름이 없음
- [x] `color-gray` 텍스트 색상이 라이트모드에서 대비가 충분치 않음
- [x] 테스트를 위해 사용했던 에디터의 불필요한 aria 속성 사용 중지
- [x] 너무 큰 highlight.js 사이즈로 인한 '큰 자바스크립트 파일에 소스 맵이 없음' 오류
