### ISSUE TITLE
ServerSide 작업 로깅 추가

### ISSUE THREAD

**Issue by pds0309** [Almondia/meca_front#259]
## Summary

ServerSide 작업 로깅 추가

Server 측에서 수행되는 작업의 경우 어떻게 처리되었는지 배포환경에서 확인하기 힘듬

<br>

## TODO

- [x] winston logger 설정
- [x] server 측 수행 작업에 대해 최소한의 로깅 설정 추가

## ETC

- [x] docker volumn 설정
- [x] log rotation 잘 되는지?
