### ISSUE TITLE
SSR 개선

### ISSUE THREAD

**Issue by pds0309** [Almondia/meca_front#271]
## Summary

페이지 응답까지 걸리는 시간 개선을 위한 SSR 처리 변경

<br>

## TODO

- [x] server api를 여러개 호출할 때 순차적으로 호출하는 부분 병렬로 개선
- [x] ssr페이지에서 server측에서 생성한 api 데이터를 그대로 동기화해 사용되는 react query hook에서 api 함수 dynamic import 처리
- [ ] ~~목록 데이터 썸네일에서 placeholder blur 이미지 만드는 작업 분리~~: 로그 확인 후 처리
