### ISSUE TITLE
serverside blur 이미지 생성 동작 개선

### ISSUE THREAD

**Issue by pds0309** [Almondia/meca_front#275]
## Summary

serverside blur 이미지 생성 동작 개선 필요

- 로컬환경과 비교해봤을 때 서버사이드에서 동시에 여러개의 blur 이미지 만드는 비동기 동작이 느림
- 이미지 `수정`은 없기 때문에 매 페이지 요청마다 blur이미지를 만들 필요 없음

<br>

## TODO

- [x] placeholder image 생성 부분 api route로 변경
- [x] nginx에 캐싱 적용

<br>

## etc

- [x] 기존 동작에 변경이 없는가?
- [x] nginx 캐싱 처리가 되는가?
