### ISSUE TITLE
일부 UI 요소 개선

### ISSUE THREAD

**Issue by pds0309** [Almondia/meca_front#285]
## Summary

일부 UI 요소 개선

<br>

## TODO

- [X] 퀴즈 히스토리 목록 모바일 스타일 개선
- [x] 퀴즈 진행 시 question text bold 처리되어있는 부분 제거
- [x] MecaCard Statistics UI 변경
- [ ] ~~실제 모바일에서 next image를 매우 크게 가져오는 문제~~

[dimensions](http://www.gregoryschmidt.ca/writing/why-are-phone-dimensions-backwards)
[dimensions2](https://www.quora.com/Are-dimensions-the-same-thing-as-pixels-px)
[devicePixelRatio](https://dev.to/daletom/optimizing-images-with-next-js-vercel-3m3n)
