### ISSUE TITLE
서버측 불필요한 처리 제거

### ISSUE THREAD

**Issue by pds0309** [Almondia/meca_front#287]
## Summary

서버측 불필요한 dehydration data 등의 처리 제거

<br>

## 문제상황

**(1)**
특정 SSR 페이지에서 dehydrate로 넘기는 데이터가 불필요하게 많아져 초기 응답시간에 영향을 줌

목록형 데이터 조회 시 에디터로 작성되는 부분들(question, description)이 불필요하게 포함되어 서버측에서 만드는 페이지의 사이즈가 매우 커짐

**(2)**

blur image 처리 api route를 캐싱하고 ssr,ssg페이지에 적용했는데 이는 권장되지 않음(추가적인 비효율적인 로드가 발생할 가능성)
cloudfront lambda@edge로 변경해보았으나 응답 지연 가능성이 매우 높음
blur image 처리 의도가 크기가 일정하지 않은 썸네일 이미지에 대해 레이아웃시프트를 방지하고자 함이었으니 width,height를 이용해 기본 blur image를 보여주도록 수정함

## TODO

- [x] history 목록 조회 api 응답에서 description html 문자열 제거
- [x] card 목록 조회 api 응답에서 description, question html 문자열 제거
- [x] placeholder image api route를 서버측에서 호출하는 부분 제거 및 기본 blur 이미지로 썸네일 blur 처리로 변경
- [x]  main page blur 이미지 처리 api가 아닌 기존 plaiceholder 직접 사용하는 방식으로 변경

![image](https://github.com/Almondia/meca_front/assets/76927397/b44efcaa-55ae-4f09-aceb-005a4b40a3df)
[참고해볼것](https://wikidocs.net/197789)
