### ISSUE TITLE
react query custom hook 구조 개선

### ISSUE THREAD

**Issue by pds0309** [Almondia/meca_front#293]
## Summary

react query custom hook 구조 개선

<br>

## TODO

- [x] client side , server side react query fetch 처리 동기화

> serverSide(prefetch or fetech query) 패칭과 clientSide(useQuery) 패칭 동기화에 중복된 코드 작성(queryKey, queryFn)이 많음
   추가 또는 수정에 약함

- [x] Like 버튼 클릭으로 호출 성공 시 내 추천 카테고리 목록 invalidation 처리 추가

- [x] 일부 동작이 중복되는 hook들 개선

<br>
