### ISSUE TITLE
axios top level await 적용

### ISSUE THREAD

**Issue by pds0309** [Almondia/meca_front#294]
## Summary

axios top level await 적용

<br>

## 이유

기존 클라이언트 측 axios로의 api 호출의 경우 대부분이 사용자 상호작용 이후에 통해 이루어지기 때문에 api fetch 함수를 늘 dynamic import로 가져와 사용했음

반복적으로 불필요하게 dynamic import 처리를 해야되는 불편함이 있음 

## TODO

- [x] tsconfig target es 설정 변경 및 axios 모듈 import를 top level await로 적용
- [x] 기존 axios api 모듈 dynamic import 제거
- [x] jest 환경에서 axios 처리
- [x] storybook 환경에서 axios 처리

<br>

## Check

- [ ] Storybook CI pass
- [ ] Storybook 배포 후 mock api 사용되는 부분 테스트
- [ ] Jest Test Pass
- [ ] 앱 build Pass
