### ISSUE TITLE
일부 컴포넌트 개선

### ISSUE THREAD

**Issue by pds0309** [Almondia/meca_front#302]
## Summary

일부 컴포넌트 UI 또는 이벤트 처리 개선

<br>

## TODO

- [x] IconButton 사이즈 유연성 개선
- [x] DropdownMenu button 분리하여 부모 측에서 버튼을 지정할 수 있도록 개선
- [x] ToggleSwitch 제거 및 카테고리 공유 설정 CheckBox로 변경
- [x] Selection => Tab 네이밍 변경 및 선택되었을 때 click event 제거

<br>
