### ISSUE TITLE
Storybook 관련개선

### ISSUE THREAD

**Issue by pds0309** [Almondia/meca_front#311]
## Summary

Storybook 관련개선

<br>

## TODO

- [x] msw handler useEffect 내에 선언되어있는 부분 수정
- [x] 정확한 UI확인을 위한 불필요한 padding 설정 제거
- [x] 불필요하게 정적 파일 등이 msw로 캡쳐링되는 문제 해결

![image](https://github.com/Almondia/meca_front/assets/76927397/c5621c5d-a1f7-4bf0-b50b-27292652d258)
