### ISSUE TITLE
Category 추가 / 수정 / 삭제 기능 추가

### ISSUE THREAD

**Issue by pds0309** [Almondia/meca_front#33]
## Summary

Category 추가 / 수정 / 삭제 기능 추가

<br>

## TODO

- [x] Category 추가, 수정, 삭제 dialog 추가
- [x] 카테고리를 카테고리 페이지에서 추가할 수 있다.
- [x] 카테고리 하나를 선택해 삭제할 수 있다.
- [x] 카테고리 하나를 선택해 이름을 수정할 수 있다.

<br>
