### ISSUE TITLE
일부 UI

### ISSUE THREAD

**Issue by pds0309** [Almondia/meca_front#333]
## Summary

일부 UI 개선

<br>

## TODO

- [ ] MecaPost Subinfo 간격
- [ ] Radio 버튼 체크 되었을 때 UI 어색한 점, 모바일에서 상호작용 범위 문제
- [ ] Input placeholder 기울임 제거
- [ ] MecaWrite Description Editor 기본 높이 수정
- [ ] QuizTimeline 모바일에서 말풍선 위치 어색한 부분
- [ ] Range input 우측 끝에 위치할 경우 짤려보이는 문제
- [ ] CardList 패칭중에도 로드 스피너 대신 스켈레톤 적용
- [ ] 다른사람 카드 상세 페이지인 경우 카테고리 보기 링크 추가
