### ISSUE TITLE
QuizPage 결과 상태 유지 처리, Scroll top 처리 추가

### ISSUE THREAD

**Issue by pds0309** [Almondia/meca_front#334]
## Summary

QuizPage Scroll top 처리 추가

<br>

## TODO

- [x] scrollIntoView hook 분리
- [x] Quiz phase 변경에 scroll event 처리 추가
- [X] QuizPhase = 'result'일 경우 unmount 시 clear하지 않고 상태 유지
