### ISSUE TITLE
Category 목록 조회 기능 추가

### ISSUE THREAD

**Issue by pds0309** [Almondia/meca_front#34]
## Summary

Category 목록 조회 기능 추가

<br>

## TODO

- [x] 목록 조회 api를 사용해 목록을 보여준다.
- [x] 이름으로 필터링 하여 조회할 수 있다.
- [x] 무한 스크롤 페이징이 된다.

<br>
