### ISSUE TITLE
api route test code 작성 및 구조 개선

### ISSUE THREAD

**Issue by pds0309** [Almondia/meca_front#351]
## Summary

api route test code 작성 및 구조 개선

- 유지보수, 기능 수정의 안정성을 위한 api route 테스트 코드 작성

- 관리하기 쉽도록 중복 동작, 관심사 분리

<br>

## TODO

- [x] node-mocks-http 세팅
- [x] 구조 개선
- [x] revalidate를 호출하는 api들 api route로 처리하고 클라이언트측에서 수행하지 않도록 수정
- [x] 도메인 관련 api rotue 테스트 코드 작성
