### ISSUE TITLE
bug fix

### ISSUE THREAD

**Issue by pds0309** [Almondia/meca_front#357]
## Summary

bug fix

<br>

## TODO

- [x] card 삭제 시 categoryId 안넘겨서 revalidation 안됨
- [x] staletime이 길어서 최신화 안되는 문제, card 추가/삭제 시 퀴즈 풀이 정보 invalidate 안됨
- [x] GlobalLoadSpinner defer time 한 번 적용되었을 때 초기화되지 않는 문제
