### ISSUE TITLE
Quiz play 시 일부 개선 사항

### ISSUE THREAD

**Issue by pds0309** [Almondia/meca_front#359]
## Summary

Quiz play 시 일부 개선 사항

<br>

## TODO

- [x] 문제 순서 shuffle 필요 - 기존 api 조회 랜덤 처리 로직 삭제로 섞을 필요성
- [x] 주관식 문제 결과 확인 Score UI 개선
- [x] OX 또는 객관식 문제 유형을 연속으로 풀 때 이전에 선택했던 항목이 다시 선택되지 않는 문제
