### ISSUE TITLE
quiz page 구조 리팩터링

### ISSUE THREAD

**Issue by pds0309** [Almondia/meca_front#361]
## Summary

quiz page 리팩터링
- quiz page에 많은 동작들이 명령형으로 작성되어있어 테스트 어렵고 읽기 힘듬
- quiz 진행 상태를 변경하고 조작하는 동작들 hook으로 분리 후 page에 선언하여 사용하도록 개선

<br>

## TODO

- [x] quizPhase hook 분리 후 적용
- [x] quizPhase, quizResult hook 테스트 코드 작성

<br>

## check

- [ ] 기존 동작에 변경이 없는가
