### ISSUE TITLE
간접적으로 테스트된 비즈니스 로직 처리 hook들

### ISSUE THREAD

**Issue by pds0309** [Almondia/meca_front#363]
## Summary

간접적으로 테스트한 비즈니스 로직 처리 hook들의 test를 추가
- 지속적으로 구조를 개선하는 등 리팩터링 작업을 하니 해당 hook들이 독립적으로 잘 동작하는 지 검증해둘 필요가 있다.
- api 명세 또는 요청/응답이 변경 또는 기능 수정이나 추가가 발생할 가능성이 지속적으로 있으니 안정성을 더해둘 필요가 있다.

<br>

## TODO

- [ ] 간접적으로 테스트 된 api 처리 hook 테스트 추가
- [ ] 추가적 검증이 필요하다고 판단되는, 테스트 되지 않은 edge case 및 function call에 대한 테스트 추가

<br>

## check

- [ ] 기존 동작을 수정하지 않았는가
