### ISSUE TITLE
memory card 등록 UI, 기능 추가

### ISSUE THREAD

**Issue by pds0309** [Almondia/meca_front#42]
## Summary

memory card 등록 UI 추가

<br>

## TODO

- [x] 문제 유형에 따라 등록 Input UI가 변경될 수 있다.
- [X] 문제 수정,추가에 따라 동작 및 UI가 변경된다.
- [X] 등록, 수정 기능 추가

<br>
