### ISSUE TITLE
카테고리 이미지 기능 구현

### ISSUE THREAD

**Issue by pds0309** [Almondia/meca_front#67]
## Summary

카테고리 카드에 섬네일 이미지 추가

<br>

## TODO

- [x] presigned url 가져오기 및 이미지 업로드 api 추가
- [x] 카테고리 등록/수정 시 섬네일 업로드 기능 추가
- [x] 카테고리 카드에 섬네일 이미지 나오도록 UI 추가

<br>
