### ISSUE TITLE
일부 컴포넌트 전반적 UI 개선

### ISSUE THREAD

**Issue by pds0309** [Almondia/meca_front#73]
## Summary

일부 컴포넌트 전반적 UI 및 태그 개선

<br>

## TODO

- [x] 썸네일 이미지 식별안됨
- [x] 버튼 사이즈
- [x] 아이콘 버튼 접근성
- [x] 네비게이션 바 사이즈
- [x] 로그인 카드 제거 및 로그인 모달 추가
- [x] input 스타일 미적용
- [x] 로고 추가
<br>

## etc

수정하며 스토리북 확인하기
