### ISSUE TITLE
공유 카테고리 목록 페이지 추가

### ISSUE THREAD

**Issue by pds0309** [Almondia/meca_front#75]
## Summary

공유 카테고리 목록 페이지 추가

<br>

## TODO

- [x] api 사용한 로직 추가
- [x] 컴포넌트 추가 및 메인 페이지 반영
- [x] 메인 페이지 UI 개선 및 기존 본인 카테고리 목록 페이지 rewrite 수정

<br>

## etc

- 내 카테고리 목록 조회 컴포넌트들과의 재사용성 잘 고려해 개발할 것
