### ISSUE TITLE
Icon 사용 설정 및 공통 Icon Components 추가

### ISSUE THREAD

**Issue by pds0309** [Almondia/meca_front#8]
## Summary

nextjs와 storybook에서 Icon 사용 설정 및 공통 Icon Components 추가

<br>

## TODO

- [x] nextjs에서 icon component를 사용할 수 있다.
- [x] storybook에서 icon component를 사용할 수 있다.
- [x] 공통 icon components를 추가한다.

<br>

### storybook에서 svg 아이콘 컴포넌트 스토리 만들 때 svg관련 에러

**문제 상황**

![image](https://user-images.githubusercontent.com/76927397/223102252-83a59215-daad-41f6-9d05-f221d8cea4c2.png)

리액트 컴포넌트로 아이콘을 사용하기 위해 `@svgr/webpack` 라는 SVG 파일을 React 컴포넌트로 변환해주는 Webpack 로더를 적용했음에도 다음과 같은 문제 발생

**원인**

svg를 컴포넌트화 하기 전에 스토리북 실행 시

기존 스토리북의 webpack 로더 규칙에서 svg 파일을 찾아 처리하고 있어서 발생한 문제

**해결**

> preview.js에 다음과 같은 설정 추가

```javascript
    const fileLoaderRule = config.module.rules.find((rule) => rule.test && rule.test.test('.svg'));
    fileLoaderRule.exclude = /\.svg$/;
```

`config.module.rules`라는 웹팩 로더 규칙에서 `.svg` 확장자 파일들을 모두 찾아 exclude설정 하여 로드하지 않도록 한 뒤

```javascript
config.module.rules.push({
      test: /\.svg$/, // svg파일에 대해
      enforce: 'pre', // 다른 로더보다 먼저 수행
      use: ['@svgr/webpack'], // 해당 로더에 svgr 모듈 사용
});
```
기존 `svgr` 로 컴포넌트로 변환해주는 설정을 사용

**해결**

![image](https://user-images.githubusercontent.com/76927397/223104664-4e94b1aa-3e96-4284-90ac-b7e398755c45.png)

**reference**

https://github.com/storybookjs/storybook/issues/9070
