### ISSUE TITLE
CardList, Card UI 개선

### ISSUE THREAD

**Issue by pds0309** [Almondia/meca_front#97]
## Summary

CategoryList UI 개선

<br>

## TODO

- [x] 중복되는 Category, Meca  List  컴포넌트 UI 스타일 개선
- [x] 중복되는 Category, Meca  Card 컴포넌트 UI 스타일 개선
- [x] 목록 카드 이미지 반응형 사이즈 개선

<br>
